### PR TITLE
Add support for custom json-based content-type

### PR DESCRIPTION
**Pull request by codyaray**
We're building on https://jsonapi.org/ and specify the content type in our OpenAPI as `application/vnd.api+json` as required by this spec.

This PR just updates it so that we can support JSON-based content-types with custom names, instead of just `application/json` (though that is the default still)

### CODE REVIEW

**Comment by ErikWittern** [comment]
@codyaray Thanks for the PR! It seems to lead to failed tests, though, which also affects https://github.com/ErikWittern/openapi-snippet/pull/35, as it builds on this one.

The issue seems to be that the example petstore_swagger.json actually defines multiple consumes and produces types, including application/json _and_ application/xml. By picking the first one, in some cases application/xml is selected, which leads to the payload being formatted as a string instead of a JSON object.

Maybe you could add to the PR so that, if multiple mime/content types are defined, it first tries to select application/json and only selects the arbitrary first type defined if application/json does not exist?

**Comment by codyaray** [comment]
We actually decided to move away from `application/vnd.json+api` so I'll just close this. :)

**Comment by kwent** [comment]
@ErikWittern I need `application/vnd.api+json` support to generate payload as well. Is this a quick fix ?

**Comment by ErikWittern** [comment]
@kwent I am really not familiar with `application/vnd.api+json`. If a `requestBody` object has `content` that uses `application/vnd.api+json` as its media type, will the description of that data also be based on JSON schema? I.e., could it be that [these checks](https://github.com/ErikWittern/openapi-snippet/blob/master/openapi-to-har.js#L93-L95) should simply also consider `application/vnd.api+json`?

**Pull request closed without merging**
